
import { Timestamp } from 'firebase/firestore';

interface InitialReview {
  author: string;
  text: string;
  reply?: {
      author: string;
      text: string;
      isVerified: boolean;
      createdAt: Timestamp;
  };
}

export const initialReviews: InitialReview[] = [
    { author: "Fisting SP", text: "Italo é um querido, educado, safado na medida, e fez uma das melhores sessões de fisting da minha vida. Sabe exatamente o que fazer, tem muita experiência. Lugar limpo e muito confortável. Já vou virar fixo." },
    { author: "AnonimoSpT", text: "Vários brinquedos, sabe usa-los, sabe fistar e inicar um passivo. Muito putao e delicioso. Chupa um cu dando tesao. Sabe arrombar, \"piss inside\"...vou repetir" },
    { author: "Edu", text: "Que delícia de carioca! Gosta do que faz, e faz com vontade. Fez tudo o que combinamos previamente, sem frescuras. Uma rola e bunda de outro planeta. Voltarei mais vezes, com certeza." },
    { author: "O Gato Puto", text: "Que experiência sensacional! Um putão de confiança! Me deixou confortável e a vontade para ir me soltando e me fez de vadia exatamente como pedi! Sai com a bucetinha arrombada e leitada, me sentindo uma fêmea bem vadia" },
    { author: "Padre Hercilio", text: "Sou padre da Igreja de verdade e não é segredo que os padres são tudo safado e eu tbm. Esse Italo me atraiu muito. Gostaria de abençoar ele com uma água benta especial: não aquela água benta comum, mas a água benta que vai jorrar do meu jato pau." },
    { author: "Mineiro em SP", text: "Italo é um puta gostoso. Desde o olhar ate os pés. E o sotaque é um charme. Domina bem, manda na situação. Alargou meu cu até onde eu aguentei e depois ainda ficou uma hora metendo sem gozar. Eu teria ficado a noite toda com a pica dele fudendo meu rabo de tão bem que ele mete. Mas da próxima vez eu vou querer ir até onde ele não aguentar mais." },
    { author: "Luca", text: "Muito simpático e gosta de entender o que você quer, realmente domina e usa bem, ansioso pra próxima vez. Tem tantos brinquedos pra usar que até me surpreendi" },
    { author: "André", text: "Ainda vou ter a honra de me ajoelhar aos seus pés e agradecer por essa oportunidade" },
    { author: "Fan", text: "Curti cada instante desses 60 min. Ele é longo e gostoso. Também é educado, gentil, confiável, no pré e o no pós atendimento. Durante a foda, o senhor da situação e eu sua serva. Apanhei na bunda até chorar e pedir pra parar. Mamei muito a rola, levei mijão no cu, cuspe na boca e claro, muita rola e porra no cu no final. Gozei com ele chupando meus mamilos e dedando meu cuzinho. Um tesão e um prazer muito grande, que recomendo demais. Vocês não vão se arrepender!" },
    { author: "Manoel", text: "Italo é uma pessoa excepcional, sem erro. Tudo com ele vale a pena .... Um ativo com pegada mas também com envolvimento Tem pelo menos 5 anos que o conheço..." },
    { author: "Sub pc", text: "Foi uma foda incrível!!!! O melhor com que eu já saí! Com certeza irei em outras oportunidades" },
    { author: "Copa", text: "Valeu a pena conhecer . Atencioso e bem safado." },
    { author: "Bezerrando", text: "Esse é um gostoso que me desatina. O fisting, os brinquedos, a pele da pica roçando no meu cu ... fenomenal. Fora o leite que é uma delícia e vale cada gota. Recomendo." },
    { author: "Fabio", text: "Um cara super profissional, sabe realizar fetiches e também sabe ser carinhoso e educado. Sou tímido e ele me deixou super a vontade e confortável. Saí com ele algumas vezes e cada vez é melhor do que a outra. Se você quer um homem que te pegue de jeito mas que também sabe te dar carinho, o Italo é esse cara. Perfeito!!!" },
    { author: "👀", text: "Italo é uma pessoa maravilhosa e quando o assunto é fetiche é o único que conheci que realmente sabe fazer, além de ter um acervo de brinquedos sexuais deliciosos Quando ele nos surpreende é de ficar louco, tipo botar na coleira mandar ajoelhar e te levar até a porta pra receber o entregador do Zé delivery ou quando do nada ele te amarra todo e te leva ao delírio (claro se a pessoa gostar) vale Muito a pena" },
    { author: "Pedro", text: "O Italo foi maravilhoso, cumpriu tudo que combinamos. Ele é muito simpático, cheguei meio sem jeito, pois, queria experimentar alguns fetiches e ele fez com maestria, conduzindo a situação e me dominando. Quando percebi ele já estava todo dentro de mim. Super recomendo. Obrigado Cara. Bjão" },
    { author: "Lucas", text: "Um tesão. Cara bacana e gente fina. Com certeza 10/10." },
    { author: "passrj", text: "soube como conduzir um iniciante excelente atendimento recomendo a todos !" },
    { author: "Jota", text: "Hoje ganhei um mestre. Um homem apaixonante. Risco é esse: vc pode se apaixonar! Italo é tudo isso que disseram aí é tudo que não dá para descrever. Um macho com pegada e que beija como ninguém." },
    { author: "MARCOS PUTA", text: "Estou cheio de tesão pra fazer uma visita, e ter esse atendimento, de qualidade, que todos tiveram." },
    { author: "Renan", text: "De 0 a 10, a note é 11. EXCELENTE" },
    { author: "João", text: "Se você curte um bom fetiche e tem receio de realizar. Ítalo é o cara! Lindo pra caramba, cheiroso, pauzudo, metedor, calmo mas quando tem que forte, sabe te deixar maluco. Impressionado com ele e com certeza já virei assíduo. Se eu indico? 1000%! Impossível se arrepender.", reply: { author: "Italo Santos", text: "Você que é uma delícia 🤤", isVerified: true, createdAt: Timestamp.now() } },
    { author: "ADV", text: "Me fez de puta. Me deu um Pau amanhecido pra mamar. Eu queria mais, ele chamou um amigo e ambos revesaram meu rabo. O amigo alargava e ele metia. Quase pedi uma DP, mas faltou coragem. Da próxima eu quero!!!! Uma delícia de homem!!!!", reply: { author: "Italo Santos", text: "😛", isVerified: true, createdAt: Timestamp.now() } },
    { author: "Pedro", text: "Dominador sáfado na hora do sexo e muito simpático e atencioso antes e depois super recomendo", reply: { author: "Italo Santos", text: "Foi recíproco a simpatia né chefe", isVerified: true, createdAt: Timestamp.now() } },
    { author: "Robson", text: "Matei a saudade deste moreno delicioso. Além do ótimo bate-papo de sempre. Te gosto, meu lindo!", reply: { author: "Italo Santos", text: "Você que é uma delícia super simpático", isVerified: true, createdAt: Timestamp.now() } },
    { author: "Adriano", text: "O Ítalo é simplesmente o melhor garoto de programa que eu já fiquei. Além dele ser lindo, charmoso, gostoso, safado, putão e muito, mas muito bom de cama, ele é um ser humano sensacional. Cara bom de papo, inteligente, educado, honesto, simpático e extremamente gentil. Sou fã dele, pude realizar vários fetiches e só tive experiências maravilhosas. Super indico o trabalho dele." },
    { author: "Garoto novo", text: "Estive com ele, e foi sensacional. O beijo dele é maravilhoso, depois transamos intensamente." },
    { author: "Lucas", text: "Pessoa maravilhosa, paciente, delicioso excelente profissional, repetiria sempre" },
    { author: "Ricardo safado", text: "Estive com esse boy no final de semana passado, ele é incrível foi a minha primeira vez realizando fetiche, ele sabe o q está fazendo, foi muito atencioso e educado e dominador ao mesmo tempo . Ele tem uma pegada gostosa e uma rola grande e deliciosa" },
    { author: "Leo", text: "Um boy perfeito. Pra quem gosta de testar seus limites com fetiches é simplesmente o melhor que encontrei. Vale a pena cada investimento." },
    { author: "Novinho Goiânia", text: "O cara é o maior gostoso, me tratou como um príncipe, e sabe meter e levar ao delírio, super recomendo" },
    { author: "Anônimo", text: "Ótimo atendimento, muito gato e um ótimo dominador" },
    { author: "B", text: "Esse homem é surreal de gostoso, te deixa a vontade, ele te controla, mas ele entende o que vc quer… que delícia!!! Quero mais vezes…" },
    { author: "Ignacio", text: "Uma delícia. Educado e safado ao mesmo tempo. Pau gostoso e soca muito." },
    { author: "Sandro", text: "Ele é uma pessoa muito especial, muito paciente, educado e carinhoso, esteve comigo sem pressa, foi um momento inesquecível, me deixou todo doido kkkk" },
    { author: "Fã_BH", text: "Há dois meses estive com ele em BH. Hoje 05/12 me mandou msg e disse q estava aqui. Não perdi tempo. O que já tinha sido ótimo no primeiro encontro, agora foi excelente. Atendimento de primeira, prazeroso e cheio de tesao e dominação . Macho gostoso, dominador. Não erro mais! Vlw meu lindo." },
    { author: "Ivan", text: "Pessoa especial, alto astral, transmite alegria de viver e inspira adorável gostosura ? tesão de putaria com respeito e carinho e super profissional. Gosta do que faz. E tem um sorriso lindo e sedutor. Vida longa. Até breve ?" },
    { author: "Igorz", text: "Bom papo, gostoso, educado, macho! E que pegada! Quero mais vezes!" },
    { author: "BH", text: "Cara muito massa! Simpático pra caramba, extremamente gostoso. Não estava conseguindo dar pra ele, mas ele foi me deixando com tesao até conseguir meter até o fundo. Estou até agora sentindo. Espero que volte logo a BH." },
    { author: "Leo", text: "Excelente atendimento. Tudo perfeito, assim como as informações que estão no site. Fotos reais, macho, dominador se você quiser e também só um bom comedor se quiser apenas transar. Mas é um cara completo, um tesao. Atendimento único, sem correria, sem ser mecânico. Se é a sua primeira vez vai nele, se é a segunda ou terceira com boy, vai nele de novo por que o atendimento é diferenciado, é próprio." },
    { author: "Luis", text: "O Ítalo é ótimo, vale muito a pena. Quero mais." },
    { author: "Paulo", text: "perfeito.....carinhoso e violento......tudo na medida certa.. Quero mais." },
    { author: "Jose", text: "Perfeito.......Uma mistura de carinhoso e intenso." },
    { author: "Eu", text: "Não tenho nem palavras pra descrever esse homem brilhante, ele é simplesmente incrível e muito confiável e faz um sexo gostoso como ninguém,,muito atencioso, carinhoso e paciente. Ele é tudo de bom!!!!" },
    { author: "Lucas", text: "Lindo , muito simpático , me deixou super a vontade a ponto de eu não saber se queria conversar mais ou fuder mais !! E gosta mesmo de meter !!" },
    { author: "Fulano.", text: "Muito gostoso esse mlk, sou casado estava afim de sentir uma parada diferente e ele me surpreendeu. Quero de novo?" },
    { author: "Anonimo", text: "O Italo e sensacional. Alem de ser um cara muito gente boa e simpático, trocamos uma ideia maneira, ele tem um bom papo. E no sexo ele é um absurdo de gostoso, uma das melhores transas da minha vida! Me levou a loucura.", reply: { author: "Alex", text: "Ítalo é muito gostoso e te deixa a vontade. Realiza como ninguém suas fantasias. Ainda é super educado. Vale a pena.", isVerified: false, createdAt: Timestamp.now() } },
    { author: "K", text: "Sem comentários É um gostoso, educado e mete muito bem. Pauzudo! Gozei muitooooooooooooo" },
    { author: "Anônimo Mzh", text: "Cara gente fina, educado, com um pau muito gostoso e bem duro. Pica boa de sentar. Recomendo a todos." },
    { author: "Carlos - Niterói", text: "Bom! Hj fui conhecer o Dom Ítalo Ele é lindo, sorriso maroto, parece um modelo! Conversamos um pouco antes! Pois é a primeira vez, que experimento isso! Ele colocou um aparelho que dá choque no cú, deixou ele piscando o tempo todo! Depois colocou uns utensílios nas mãos e pés, me amordacou (tudo com meu consentimento), depois me comeu 2 vezes, até ele gozar! Que cara gostoso! Ele bj os meus mamilos e mordiscou-os, deixando extasiado! Quero-o de novo!" },
    { author: "@", text: "Acabei de sair do apto Ítalo. Ambiente limpo, de fácil acesso e o atendimento dele é ótimo! Foi minha primeira experiência com um fetichista e foi fantástico! Espero poder voltar!" },
    { author: "Robson", text: "Lindo, gostoso, tranquilo, muito gente boa, pegada inigualável. O Ítalo sabe o que faz! Apesar da pouca idade, é um doutos em matéria de dar prazer." },
    { author: "Francisco Rio de Janeiro", text: "O que eu mais gostei no Itálo foi tudo, rss. Realmente ele me recebeu muito bem, me deu o que eu queria, e incansável me fez sentir e ter uma experiência única ao lado dele.", reply: { author: "Gab", text: "Ele é muito simpático, gostoso e fode muito bem. Eu amei.", isVerified: false, createdAt: Timestamp.now() } },
    { author: "De outro estado", text: "Quando falei a primeira com o Ítalo eu pedi pra ele fazer uns fetiches bem loucos comigo. Fui até ele acreditando que ia ser como os outros que prometem e não cumprem...Ele cumpriu tudo o que combinamos e muito mais. O cara é fantástico! Super educado e simpático, mas sabe impor respeito na hora do sexo. Se eu morasse na mesma cidade com ele ia querer sair toda semana com ele hahaha. Ah, ele leva a segurança do cliente bem a sério e sabe respeitar seus limites. Recomendo pra caramba!" },
    { author: "Luiz", text: "Garoto e bom demais" },
    { author: "Putao bare", text: "Chupou meu cu demorado, meteu a mão na minha cuceta, me deu um mijada dentro e finalizou com um leitada dentro no pelo." },
    { author: "Ale", text: "Estive com ele semana passada, pedi uma sessão de cbt, com direito a chicote, vela quente e choque, tudo isso com as mãos e os pés algemados? cara, que tesão!" },
    { author: "Gabriel Castro", text: "Fui convidado para atender um cliente com Don Ítalo em São Paulo SP, me surpreendeu com o excelente atendimento, para quem procura humilhação, dominação o garoto está de parabéns, ainda não conheçi ninguém do nível dele. Satisfação garantida, conduz o atendimento sem ser mecânico e de qualidade." },
    { author: "Leh", text: "Ítalo super gente boa, bom de papo e atraente, foi a minha primeira experiência como Sub com ele e gostei demais, soube me dominar muito bem e meu muito prazer! Pra quem é iniciante como eu, super recomendo!!!" },
    { author: "Mineiro", text: "Já estive com Ítalo duas vezes. Além de saber brincar direitinho, ele tem um papo muito agradável. Domina muito bem e tem uma boa coleção de acessórios." },
    { author: "Branquinha", text: "Virei puta de vestidinho vagabundo. Apanhei como merecia. Levei porra na cara. Só fiz o que ele mandava. Gostei tanto de ser tratada assim que voltei e não queria ir embora. Me arregaçou. Domínio sedutor. Ítalo é daqueles personagens da literatura erótica e sdm. Nível internacional. Ele é escavador de desejos não ditos." },
    { author: "Putão", text: "Foda sensacional, já fiz várias sessões de dominação e putaria sem limites com Italo. Sabe dominar, humilhar, soca e fista até arrombar meu cu. Já me deu muita porra e mijo. Sem contar q ele tem todos os brinquedos e acessórios q eu podia imaginar. Até anaconda gigante ele enfiou em mim. Recomendo pra quem tem experiência e também pra quem quer ser iniciado, porque além de muito puto, ele é educado, limpo e seguro." },
    { author: "Rogfaria", text: "Se você gosta de ser tratado como puta, apanhar e tomar leite, esse é o cara! Macho, bonito, gostoso, educado e puto. Super recomendo!" },
    { author: "Gato bh 32a", text: "Lindo, educado, respeita os limites e sabe dominar. Não vejo a hora dele voltar pra BH pra servi-lo novamente. Bebi mijao, me vestiu de puta, usei coleirinha, algemas, me exibiu pro pessoal da República como sua putinha, fiz video. Tesão. Qro denovo hehehe. Saudades lindo." },
    { author: "Lu", text: "É bem difícil achar um garoto que conheça de verdade bdsm, mas o Ítalo é um mestre no assunto, sem falar que tem ótimos acessórios, e sabe muito bem usar, fiquei o tempo todo babando de tesão, valeu cada centavo...o bom é que no dia seguinte vai se olhar no espelho e lembrar...."},
    { author: "Diego-Florwsta-Bh-Rj", text: "Ele MOLEQUE melhor que nas fotos.e vídeos.... Melhor que.vc magina.. Recomemdo" },
    { author: "Luixx", text: "Sai com ele ontem, melhor de todos." },
    { author: "Cd 25a sp", text: "Encontrei Dom Ítalo no último sábado e nunca me senti tão humilhada na minha vida. Me tratou igual uma puta de verdade e arrombou bem minha cuceta. Sem falar que o pau dele é perfeito, o local é ótimo e os acessórios são excelentes para quem quer ficar cada vez mais largo" },
    { author: "F", text: "Demais o Ítalo!" },
    { author: "sub Jock", text: "O Ítalo é Perfeito e Inesquecível ! Não se iluda com a pouca idade dele, porque ele vai te surpreender. Pegada boa e perfeita, nem mais nem menos do que deveria ser e Faz com vontade. Impossível você ficar sem vontade de: quero mais." },
    { author: "Bebe", text: "Com esse cara realizei meu sonho de ser a passiva mais puta do mundo. Inesquecível." },
    { author: "Batman", text: "Melhor cara que já sai. Podem Ir sem medo, o cara vai sabe tratar um Viado do jeito que viado merece." },
    { author: "Anonimo", text: "O Ítalo é daquelas pessoas que deixa saudades. Super educado, safado, nada apressado, me fez gozar sem eu nem encostar no pau. Fala bastante putaria e domina muito bem. Isso sem falar nos inúmeros brinquedos que ele tem na casa dele" },
    { author: "Garoto safado", text: "Tesao de macho deve levar o puto a loucura. Eu queria ser obsecrados desse macho." },
    { author: "Pankado", text: "Sempre me oferece um adicional bom, pra puxar no pau. Chupa bem um cu, bomba bem e tem brinquedos gostosos. Tá sempre f1 e gosta do que faz. Nota 10." },
    { author: "Trabalha em ipanema", text: "Piroca gostosa , baste leite soca gostoso e carinhoso .Quando posso vou sempre fude com ele pica muito gostosa" },
    { author: "Italo", text: "leito farto" },
    { author: "Rodrigo", text: "Que pau gostoso de mamar. Eh grande mesmo. E jorra bem." },
];
