##############################################################################
# App Engine Configuration - Studio Italo Santos
# Projeto: YOUR_FIREBASE_PROJECT_ID
##############################################################################

runtime: nodejs20
env: standard
instance_class: F2

# ========================================
# Scaling Configuration
# ========================================
automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.75
  min_idle_instances: 0
  max_idle_instances: 2
  min_pending_latency: 30ms
  max_pending_latency: automatic

# ========================================
# Environment Variables
# ========================================
env_variables:
  NODE_ENV: "production"
  NEXT_TELEMETRY_DISABLED: "1"
  
# ========================================
# VPC Access (descomente se usar Cloud SQL)
# ========================================
# vpc_access_connector:
#   name: "projects/YOUR_FIREBASE_PROJECT_ID/locations/southamerica-east1/connectors/italosantos-connector"

# ========================================
# Handlers - Rotas da aplicação
# ========================================
handlers:
  # Static files (_next/static)
  - url: /_next/static
    static_dir: .next/static
    secure: always
    expiration: 365d
    http_headers:
      Cache-Control: "public, max-age=31536000, immutable"
  
  # Public files
  - url: /(.+\.(ico|png|jpg|jpeg|svg|gif|webp|woff|woff2|ttf|eot|css|js|json|xml|txt))$
    static_files: public/\1
    upload: public/.*
    secure: always
    expiration: 1d
    http_headers:
      Cache-Control: "public, max-age=86400"
  
  # Next.js API routes e pages
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto

# ========================================
# Network Settings
# ========================================
network:
  session_affinity: true

# ========================================
# Resources (descomente para ajustar)
# ========================================
# resources:
#   cpu: 1
#   memory_gb: 0.5
#   disk_size_gb: 10

# ========================================
# Liveness e Readiness Checks
# ========================================
liveness_check:
  path: "/api/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

readiness_check:
  path: "/api/health"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300